<a href="https://colab.research.google.com/github/raphaelmendes18/MLND-Quadcopter/blob/master/Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Projeto 1 - Análise de Algoritmos:
### Multiplicação de Matrizes

- Método 1: Multiplicação Comum
- Método 2: Algoritmo de Strassen

In [0]:
import numpy as np
import matplotlib as plt
import seaborn as sns
import random

class Matrix():
  
  def __init__(self, n_rows=10, n_cols=10, min_range = 1, max_range = 100,matrix = None):
    
    if matrix is None:
      matrix = []
      for i in range(0,n_cols):
        tuple = []
        for j in range(0,n_rows):
          tuple.append(random.randint(min_range, max_range))
        matrix.append(tuple)

      self.matrix = np.matrix(matrix)
      self.n_rows = n_rows
      self.n_cols = n_cols
    else:
      self.matrix = np.matrix(matrix)
      self.n_rows = n_rows
      self.n_cols = n_cols
  
  def __repr__(self):
    return str(self.matrix)
  
  @staticmethod
  def multiply(A, B):
    
    if A.n_cols != B.n_rows:
      raise ValueError('Matrices cannot be multiplied n_cols != n_rows')
    else:
      result_matrix = []
      for i in range(0,A.n_rows): #row iterator of Matrix A
        result_row = []
        for k in range(0,B.n_cols): #column iterator of Matrix B
          value = 0
          for j in range(0,A.n_cols): #column iterator of Matrix A and row iterator of Matrix B
            value += int(A.matrix[[i],[j]]) * int(B.matrix[[j],[k]])
          result_row.append(value)
        result_matrix.append(result_row)
      return Matrix(matrix=result_matrix,n_rows=A.n_rows,n_cols=B.n_cols)
    
  def multiply_strassen(A,B):
    pass
  
  def print_matrix(self):
    print("MATRIX WITH SHAPE: {}".format(self.matrix.shape))
    for i in range(0,self.n_rows):
      print(self.matrix[[i]])
    

In [67]:
A = Matrix()
B = Matrix()
result_mult = Matrix.multiply(A,B)

result_mult.print_matrix()


MATRIX WITH SHAPE: (10, 10)
[[18521 20479 33238 26554 39044 12767 27695 41641 36816 35734]]
[[20757 13667 30949 30772 31121 17042 32314 36080 27929 26872]]
[[21502 22506 36974 29547 39646 15232 32571 41467 40264 41604]]
[[25163 25988 36245 35150 44018 21039 29994 47052 36482 39644]]
[[23649 23540 38341 32611 42345 19015 30614 41030 37551 42770]]
[[25180 23578 40028 38601 44128 21626 37995 44223 39944 47272]]
[[24169 21417 35847 31822 37564 19214 30113 42835 34074 32150]]
[[20268 19863 36138 29667 42265 16504 29986 39117 36207 44954]]
[[20416 18339 40500 36009 37281 19575 36732 38789 33159 37152]]
[[16546 13536 26190 26554 28057 15428 24712 32492 22949 22578]]


In [50]:
np.matrix(result_mult)

matrix([[[[16175, 11739, 19084, 14362, 21526, 19140, 23668, 16605, 15319, 21089], [23249, 23928, 20906, 13648, 22476, 19919, 24500, 27786, 16556, 27532], [20575, 21371, 23485, 15404, 30958, 29639, 30076, 27017, 18845, 28147], [22163, 24243, 23069, 24137, 37121, 34898, 35436, 32889, 27325, 33187], [30130, 26698, 33161, 16331, 36503, 25875, 33924, 38026, 28391, 37048], [24269, 24498, 26563, 20993, 40648, 36885, 39725, 33957, 28116, 34061], [22944, 16077, 27674, 21166, 33001, 23899, 32975, 28921, 26547, 34362], [26528, 23498, 29117, 21837, 40013, 34522, 37652, 35071, 30548, 35970], [21018, 19689, 23446, 13972, 26852, 27193, 28998, 24293, 19605, 26711], [20881, 23314, 31836, 15413, 38615, 31423, 35818, 29216, 25729, 30878]]]],
       dtype=object)